"""
Recommendations API Router.
Handles loading, analyzing, applying, and gathering feedback for safety-validated crowd recommendations.
"""
from typing import Annotated

import uuid
from datetime import datetime, UTC
from fastapi import APIRouter, Depends, HTTPException, Header, Query, status
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from sqlalchemy import func, case
import redis.asyncio as aioredis
import json
from backend.app.core.database import get_db, get_redis_client, USE_REDIS
from backend.app.models.models import Recommendation, Task
from backend.app.schemas.schemas import RecommendationResponse, RecommendationFeedback

router = APIRouter()

@router.get("", response_model=list[RecommendationResponse], responses={500: {"description": "Failed to fetch recommendations"}})
async def list_recommendations(
    db: Annotated[AsyncSession, Depends(get_db)],
    trigger_event_id: uuid.UUID | None = None,
    limit: Annotated[int, Query(ge=1, le=100)] = 20,
    offset: Annotated[int, Query(ge=0)] = 0
):
    """
    Retrieves a paginated list of crowd management recommendations generated by the platform.
    
    Optional filters:
    - `trigger_event_id`: Fetch only recommendations associated with a specific operational alert.
    """
    try:
        query = select(Recommendation)
        if trigger_event_id:
            query = query.where(Recommendation.trigger_event_id == trigger_event_id)
        query = query.order_by(Recommendation.generated_at.desc()).limit(limit).offset(offset)

        result = await db.execute(query)
        recommendations = result.scalars().all()
        return recommendations
    except Exception:
        from backend.app.core.logging import logger
        logger.exception("Failed to fetch recommendations")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to fetch recommendations. Please try again."
        )

@router.get("/stats", status_code=status.HTTP_200_OK, responses={500: {"description": "Failed to compile recommendation metrics"}})
async def get_recommendation_stats(
    db: Annotated[AsyncSession, Depends(get_db)]
):
    try:
        # Aggregate directly in SQL — avoids full table scan into Python memory
        agg_query = select(
            func.count(Recommendation.id).label("total_count"),
            func.avg(Recommendation.reasoning_time_ms).label("avg_reasoning_time_ms"),
            func.sum(
                case((Recommendation.validation_status == "VALIDATED", 1), else_=0)
            ).label("validated_count"),
            func.sum(
                case((Recommendation.validation_status != "VALIDATED", 1), else_=0)
            ).label("violation_count"),
        )
        agg_result = await db.execute(agg_query)
        row = agg_result.one()

        total_count = row.total_count or 0
        if total_count == 0:
            return {
                "total_count": 0,
                "avg_reasoning_time_ms": 0.0,
                "validated_count": 0,
                "violation_count": 0,
                "total_co2_saved_kg": 0.0,
                "provider_stats": {}
            }

        # Fetch only fields needed for non-aggregatable columns (co2, provider)
        detail_result = await db.execute(
            select(
                Recommendation.expected_impact,
                Recommendation.model_version,
            )
        )
        detail_rows = detail_result.all()

        total_co2 = 0.0
        provider_stats: dict[str, int] = {}
        for impact, model in detail_rows:
            if impact and isinstance(impact, dict):
                total_co2 += float(impact.get("co2_saved_kg", 0.0))
            key = model or "Unknown Provider"
            provider_stats[key] = provider_stats.get(key, 0) + 1

        return {
            "total_count": total_count,
            "avg_reasoning_time_ms": round(float(row.avg_reasoning_time_ms or 0.0), 1),
            "validated_count": int(row.validated_count or 0),
            "violation_count": int(row.violation_count or 0),
            "total_co2_saved_kg": round(total_co2, 2),
            "provider_stats": provider_stats
        }
    except Exception:
        from backend.app.core.logging import logger
        logger.exception("Failed to fetch recommendation statistics")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to compile recommendation metrics."
        )

from backend.app.core.auth import verify_api_key

async def _get_idempotency_cache(redis_client: aioredis.Redis, idempotency_key: uuid.UUID | None) -> dict | None:
    if not (idempotency_key and USE_REDIS):
        return None
    idemp_redis_key = f"idempotency:apply:{idempotency_key}"
    try:
        cached_val = await redis_client.get(idemp_redis_key)
        if cached_val:
            return json.loads(cached_val)
    except Exception as e:
        from backend.app.core.logging import logger
        logger.warning(f"Idempotency cache read failed: {e}")
    return None

async def _set_idempotency_cache(redis_client: aioredis.Redis, idempotency_key: uuid.UUID | None, response_payload: dict):
    if not (idempotency_key and USE_REDIS):
        return
    idemp_redis_key = f"idempotency:apply:{idempotency_key}"
    try:
        await redis_client.setex(
            idemp_redis_key,
            86400,
            json.dumps(response_payload)
        )
    except Exception as e:
        from backend.app.core.logging import logger
        logger.warning(f"Idempotency cache write failed: {e}")

async def _create_and_dispatch_tasks(db: AsyncSession, redis_client: aioredis.Redis, rec: Recommendation) -> list[uuid.UUID]:
    """
    Spawns individual ground tasks from a recommendation, saves them to the DB,
    and publishes alerts via Redis or local pubsub bus.
    """
    created_tasks = []
    from backend.app.core.database import local_pubsub_bus
    for action in rec.candidate_actions:
        task_id = uuid.uuid4()
        task = Task(
            id=task_id,
            recommendation_id=rec.id,
            assigned_user_id=None,
            assigned_role=rec.target_role if rec.target_role in ["VOLUNTEER", "SECURITY"] else "VOLUNTEER",
            details=action,
            status="DISPATCHED",
            created_at=datetime.now(UTC),
            updated_at=datetime.now(UTC)
        )
        db.add(task)
        created_tasks.append(task_id)

        task_alert = {
            "id": str(task_id),
            "details": action,
            "role": task.assigned_role,
            "status": "DISPATCHED"
        }
        if USE_REDIS:
            try:
                await redis_client.publish("tasks:stream", json.dumps(task_alert))
            except Exception as e:
                from backend.app.core.logging import logger
                logger.warning(f"Failed to publish task stream alert to Redis: {e}")
                local_pubsub_bus.publish(json.dumps(task_alert))
        else:
            local_pubsub_bus.publish(json.dumps(task_alert))
    return created_tasks

@router.post("/{recommendation_id}/apply", status_code=status.HTTP_200_OK, responses={404: {"description": "Recommendation not found"}, 500: {"description": "Internal server error"}})
async def apply_recommendation(
    recommendation_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    redis_client: Annotated[aioredis.Redis, Depends(get_redis_client)],
    _: Annotated[str, Depends(verify_api_key)],
    idempotency_key: Annotated[uuid.UUID | None, Header(alias="Idempotency-Key")] = None
):
    """
    Applies a generated recommendation, automatically converting the candidate actions
    into operational dispatch tasks for ground staff.
    
    Includes idempotency checks to prevent duplicate execution of the same action list.
    """
    # 1. Idempotency Check
    cached_val = await _get_idempotency_cache(redis_client, idempotency_key)
    if cached_val:
        return cached_val

    try:
        # 2. Fetch Recommendation
        result = await db.execute(select(Recommendation).where(Recommendation.id == recommendation_id))
        rec = result.scalars().first()
        if not rec:
            raise HTTPException(status_code=404, detail="Recommendation not found")

        if rec.validation_status == "APPROVED":
            return {"status": "already_applied", "recommendation_id": str(recommendation_id)}

        if rec.validation_status == "POLICY_VIOLATION":
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Cannot apply recommendation with validation_status=POLICY_VIOLATION due to active safety policy breaches."
            )

        # 3. Transition State
        rec.validation_status = "APPROVED"
        rec.accepted = True
        rec.applied = True

        # 4. Create & Dispatch Tasks
        created_tasks = await _create_and_dispatch_tasks(db, redis_client, rec)

        await db.commit()

        response_payload = {
            "status": "success",
            "recommendation_id": str(recommendation_id),
            "dispatched_tasks": [str(t_id) for t_id in created_tasks]
        }

        # 5. Cache response for idempotency
        await _set_idempotency_cache(redis_client, idempotency_key, response_payload)

        return response_payload

    except HTTPException:
        raise
    except Exception:
        await db.rollback()
        from backend.app.core.logging import logger
        logger.exception(f"Failed to apply recommendation {recommendation_id}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to apply recommendation. Please try again."
        )

@router.post("/{recommendation_id}/feedback", status_code=status.HTTP_200_OK, responses={404: {"description": "Recommendation not found"}, 500: {"description": "Internal server error"}})
async def submit_feedback(
    recommendation_id: uuid.UUID,
    feedback: RecommendationFeedback,
    db: Annotated[AsyncSession, Depends(get_db)],
    _: Annotated[str, Depends(verify_api_key)]
):
    try:
        result = await db.execute(select(Recommendation).where(Recommendation.id == recommendation_id))
        rec = result.scalars().first()
        if not rec:
            raise HTTPException(status_code=404, detail="Recommendation not found")

        # Update feedback loop fields
        rec.accepted = feedback.accepted
        rec.applied = feedback.applied
        rec.feedback_rating = feedback.feedback_rating
        rec.feedback_comments = feedback.feedback_comments

        # Mocking an effectiveness score logic for the vertical slice:
        # High rating + accepted gives high effectiveness
        rec.effectiveness_score = float(feedback.feedback_rating) / 5.0 if feedback.accepted else 0.0
        rec.validation_status = "EVALUATED"

        await db.commit()
        return {
            "status": "success",
            "recommendation_id": str(recommendation_id),
            "effectiveness_score": rec.effectiveness_score
        }
    except HTTPException:
        raise
    except Exception:
        await db.rollback()
        from backend.app.core.logging import logger
        logger.exception(f"Failed to record feedback for recommendation {recommendation_id}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail="Failed to record feedback. Please try again."
        )
